name: 打包Python应用

on:
  workflow_dispatch:  # 保留手动触发选项

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: 签出代码
        uses: actions/checkout@v3

      - name: 设置Python环境
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 安装UPX
        uses: crazy-max/ghaction-upx@v3
        with:
          install-only: true

      - name: 打包应用
        run: |
          pyinstaller -F main.py --windowed -n telegram_info_export --add-data "assets\logo.png;assets" --add-data "app\about.md;app" --add-data "style\style.qss;style" --upx-dir "$UPX_PATH"

      - name: 上传构建产物
        uses: actions/upload-artifact@v4
        with:
          name: telegram_info_export
          path: ./dist/telegram_info_export.exe
          retention-days: 90  # 可选，设置保留期限，默认为90天
